# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: meem-api

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  timeout: 30
  # logs:
  #   websocket: true
  environment:
    SERVERLESS: true
    LOG_LEVEL: ${env:LOG_LEVEL, 'debug'}
    ENABLE_REQUEST_LOGGING: ${env:ENABLE_REQUEST_LOGGING, 'false'}
    ORM_DISABLE: ${env:ORM_DISABLE, 'true'}
    INFURA_ID: ${env:INFURA_ID, ''}
    MEEM_PROXY_ADDRESS: ${env:MEEM_PROXY_ADDRESS, ''}
    NETWORK: ${env:NETWORK, ''}
    WALLET_PRIVATE_KEY: ${env:WALLET_PRIVATE_KEY, ''}
    GENERATE_SHARED_TYPES: ${env:GENERATE_SHARED_TYPES, 'false'}
    GITHUB_KEY: ${env:GITHUB_KEY, ''}
    CORS_ALLOW_ALL: ${env:CORS_ALLOW_ALL, 'true'}
    APP_AWS_ACCESS_KEY_ID: ${env:APP_AWS_ACCESS_KEY_ID, ''}
    APP_AWS_SECRET_ACCESS_KEY: ${env:APP_AWS_SECRET_ACCESS_KEY, ''}
    ENABLE_TEST_ENDPOINTS: ${env:ENABLE_TEST_ENDPOINTS, ''}
    DYNAMODB_SOCKETS_TABLE: ${env:DYNAMODB_SOCKETS_TABLE, ''}
    AWS_WEBSOCKET_GATEWAY_URL: ${env:AWS_WEBSOCKET_GATEWAY_URL, ''}
    LAMBDA_MINT_FUNCTION: ${env:LAMBDA_MINT_FUNCTION, ''}
    S3_BUCKET: ${env:S3_BUCKET, ''}
    MORALIS_API_KEY: ${env:MORALIS_API_KEY, ''}
    JSON_RPC_MAINNET: ${env:JSON_RPC_MAINNET, 'https://speedy-nodes-nyc.moralis.io/47bc53fc4b72dbd2d8582fea/eth/mainnet'}
    JSON_RPC_RINKEBY: ${env:JSON_RPC_RINKEBY, 'https://speedy-nodes-nyc.moralis.io/47bc53fc4b72dbd2d8582fea/eth/rinkeby'}
    JSON_RPC_POLYGON: ${env:JSON_RPC_POLYGON, 'https://speedy-nodes-nyc.moralis.io/47bc53fc4b72dbd2d8582fea/polygon/mainnet'}
    ENABLE_WHITELIST_TEST_DATA: ${env:ENABLE_WHITELIST_TEST_DATA, 'false'}
    MAX_GAS_PRICE_GWEI: ${env:MAX_GAS_PRICE_GWEI, '50'}
    MIN_GASE_PRICE_GWEI: ${env:MIN_GASE_PRICE_GWEI, '31'}
    GAS_ESTIMATE_THRESHOLD_GWEI: ${env:GAS_ESTIMATE_THRESHOLD_GWEI, '10'}
    DISABLE_MIGRATIONS: ${env:DISABLE_MIGRATIONS, 'true'}
    DISABLE_ORM_SYNC: ${env:DISABLE_ORM_SYNC, 'true'}
    ENABLE_CONTRACT_LISTENERS: ${env:ENABLE_CONTRACT_LISTENERS, 'false'}

package:
  excludeDevDependencies: true
  include:
    - build/**
    - src/types/meem.generated.ts
    - src/lib/meem-badge.png
  exclude:
    - .circleci/**
    - .vscode/**
    - backup/**
    - coverage/**
    - docker/**
    - docs/**
    - load-testing/**
    - scripts/**
    - src/**
    - tmp/**

functions:
  mint:
    handler: build/serverless/mint.handle
    timeout: 300
    memorySize: 512
  meemIdUpdate:
    handler: build/serverless/meemIdUpdate.handle
    timeout: 300
  images:
    handler: build/serverless/handler.handle
    memorySize: 768
    events:
      - httpApi:
         method: '*'
         path: '/images/1.0/{p1}'
      - httpApi:
         method: '*'
         path: '/images/1.0/{p1}/{p2}'
      - httpApi:
         method: '*'
         path: '/images/1.0/{p1}/{p2}/{p3}'
  catchAll:
    handler: build/serverless/handler.handle
    events:
      - httpApi:
         method: '*'
         path: '/api/1.0/{p1}'
      - httpApi:
         method: '*'
         path: '/api/1.0/{p1}/{p2}'
      - httpApi:
         method: '*'
         path: '/api/1.0/{p1}/{p2}/{p3}'
      - httpApi:
         method: '*'
         path: '/'
  sockets:
    handler: build/serverless/socket.handle
    events:
      - websocket: $connect
      - websocket: $disconnect
      - websocket: $default
  cron:
    handler: build/serverless/cron.handle
    timeout: 600
    events:
      - schedule:
          rate: rate(1 minutes)
          # CHANGE THIS TO "true" TO RUN CRONS
          enabled: true
          input:
            job: TwitterCron

