version: 2
jobs:
  deploy_sls_dev:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: cp .yarnclean.ci .yarnclean
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn deploy:dev
  deploy_sls_stage:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: cp .yarnclean.ci .yarnclean
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn deploy:staging
  deploy_sls_prod:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: cp .yarnclean.ci .yarnclean
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn deploy:production
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run test
  release:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"
      - run: yarn run release
workflows:
  version: 2
  do_build:
    jobs:
      # TODO: Enable tests
      # - test:
      #     context: private_packages
      #     filters:
      #       branches:
      #         ignore:
      #           - master
      - release:
          context: private_packages
          filters:
            branches:
              only:
                - dev
                - stage
                - master
      # Uncomment to deploy via serverless
      - deploy_sls_dev:
          context: api_dev
          filters:
            branches:
              only:
                - dev
      - deploy_sls_stage:
          context: api_stage
          filters:
            branches:
              only:
                - stage
      - deploy_sls_prod:
          context: api_prod
          filters:
            branches:
              only:
                - master
