version: 2.1
jobs:
  deploy_sls_prod:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run: touch .env
      - run: cp .yarnclean.ci .yarnclean
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn deploy:production
  test:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run: touch .env
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run test
  release:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"
      - run: yarn run release
workflows:
  do_build:
    jobs:
      # TODO: Enable tests
      - test:
          context: epm_api_prod
          filters:
            branches:
              ignore:
                - master
                - stage
                - dev
      - release:
          context: private_packages
          filters:
            branches:
              only:
                - dev
                - stage
                - master
      - deploy_sls_prod:
          context: epm_api_prod
          filters:
            branches:
              only:
                - master
